#!/usr/bin/python
# -*- coding: utf-8 -*-
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = '''
---
module: hello_module
short_description: Returns a greeting message.
version_added: "1.0"
author: yourname
description:
  - This basic custom module greets the user by the provided name.
options:
  name:
    description:
      - The name to greet.
    required: true
    type: str
'''

EXAMPLES = '''
- name: Greet the world
  hello_module:
    name: "World"
'''

RETURN = '''
message:
  description: The greeting message generated by the module.
  type: str
  returned: always
'''

from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec={
            'name': {'type': 'str', 'required': True}
        },
        supports_check_mode=True
    )

    name = module.params['name']
    message = "Hello, {}!".format(name)

    result = dict(
        changed=False,
        message=message
    )
    module.exit_json(**result)


if __name__ == '__main__':
    main()
